sonar.projectKey=fooddeliveryapplication
sonar.projectName=Food Delivery Application
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://devops.alacritysys.com/sonar
sonar.login=squ_3cb23ed8253d6144d73ab6c7c8d6afe75bd00cbb